# Generated by Django 4.1.4 on 2022-12-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faceInImage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pic", name="picture", field=models.FileField(upload_to=""),
        ),
    ]
