# Generated by Django 4.1.4 on 2022-12-19 06:31

from django.db import migrations, models
import faceInImage.models


class Migration(migrations.Migration):

    dependencies = [
        ("faceInImage", "0002_alter_pic_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pic",
            name="picture",
            field=models.FileField(upload_to=faceInImage.models.content_file_name),
        ),
    ]
